version: '3.8'

services:
  add_service:
    build:
      context: ./add_service
    ports:
      - "5000:5000"
    networks:
      - calc-network

  multiply_service:
    build:
      context: ./multiply_service
    ports:
      - "5001:5001"
    networks:
      - calc-network

  test_runner:
    build:
      context: .
      dockerfile: test_runner/Dockerfile
    volumes:
      - ./Pipfile:/app/Pipfile  # Mount only the Pipfile
      - ./Pipfile.lock:/app/Pipfile.lock  # Mount Pipfile.lock for dependency caching
      - ./integration_test:/app/integration_test  # Mount only the test code
    working_dir: /app
    command: ["pipenv", "run", "pytest", "integration_test/test_integration.py"]
    networks:
      - calc-network
    depends_on:
      - add_service
      - multiply_service


networks:
  calc-network:
    driver: bridge
